BEGIN;

CREATE TABLE IF NOT EXISTS material_source_files (
  material_source_file_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_id INTEGER NOT NULL REFERENCES material_sources(source_id) ON DELETE CASCADE,
  file_name TEXT NOT NULL,
  mime_type TEXT,
  file_data BYTEA NOT NULL,
  uploaded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_material_source_files_source_id
  ON material_source_files(source_id);

CREATE TABLE IF NOT EXISTS material_property_files (
  material_property_file_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  material_property_id INTEGER NOT NULL REFERENCES material_properties(material_property_id) ON DELETE CASCADE,
  file_name TEXT NOT NULL,
  mime_type TEXT,
  file_data BYTEA NOT NULL,
  uploaded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_material_property_files_property_id
  ON material_property_files(material_property_id);

COMMIT;
