BEGIN;

CREATE TABLE IF NOT EXISTS material_sources (
  source_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  material_id INTEGER NOT NULL REFERENCES materials(material_id) ON DELETE RESTRICT,

  supplier TEXT,
  brand TEXT,
  model_or_catalog_no TEXT,
  lot_number TEXT,

  date_ordered DATE,
  date_received DATE,

  quality_rating_label TEXT,
  quality_rating_score INTEGER,
  evaluation_notes TEXT,
  is_evaluated BOOLEAN NOT NULL DEFAULT FALSE,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  updated_by INTEGER REFERENCES users(user_id),

  CONSTRAINT material_sources_quality_rating_label_chk
    CHECK (
      quality_rating_label IS NULL OR
      quality_rating_label IN ('good', 'ok', 'bad', 'tbd')
    ),
  CONSTRAINT material_sources_quality_rating_score_chk
    CHECK (
      quality_rating_score IS NULL OR
      (quality_rating_score BETWEEN 1 AND 5)
    )
);

CREATE INDEX IF NOT EXISTS idx_material_sources_material_id
  ON material_sources(material_id);

CREATE INDEX IF NOT EXISTS idx_material_sources_lot_number
  ON material_sources(lot_number);

ALTER TABLE material_instances
  ADD COLUMN IF NOT EXISTS source_id INTEGER;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'material_instances_source_id_fkey'
  ) THEN
    ALTER TABLE material_instances
      ADD CONSTRAINT material_instances_source_id_fkey
      FOREIGN KEY (source_id)
      REFERENCES material_sources(source_id)
      ON DELETE SET NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_material_instances_source_id
  ON material_instances(source_id);

CREATE TABLE IF NOT EXISTS material_properties (
  material_property_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  material_instance_id INTEGER NOT NULL REFERENCES material_instances(material_instance_id) ON DELETE CASCADE,

  specific_capacity_mAh_g NUMERIC,
  density_g_ml NUMERIC,
  notes TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  updated_by INTEGER REFERENCES users(user_id),

  CONSTRAINT material_properties_instance_unique
    UNIQUE (material_instance_id),
  CONSTRAINT material_properties_specific_capacity_chk
    CHECK (
      specific_capacity_mAh_g IS NULL OR
      specific_capacity_mAh_g >= 0
    ),
  CONSTRAINT material_properties_density_chk
    CHECK (
      density_g_ml IS NULL OR
      density_g_ml >= 0
    )
);

CREATE INDEX IF NOT EXISTS idx_material_properties_instance_id
  ON material_properties(material_instance_id);

COMMIT;
